from book import BOOK

LINES = {
    'computer': (  # 0.37 seconds
        ("IN THE LAND OF THE DRAGON",),
        ("EXCHANGE OF APPLES",),
        ("A MESSAGE FROM JUPITER",),
        ("A PEANUT FOR SEMELIA",),
        ("A COMMODORE AT TRAFALGAR",),
        ("APRICOTS AND NECTARINES",),
        ("THE GENIE IN THE CHURCH",),
        ("SHARP DAGGERS CONCEALED",),
        ("EMPEROR WANG MOURNS",),
        ("HE CARRIES THE TORCH",),
        ("THE VICTOR REJOICES",),
        ("A FORTUNE IS LOST",),
        ("A PET TAKES FLIGHT",),
        ["key goes here"]
    ),

    'jesus': (  # 2m 24.8 seconds
        ("AN UNWANTED CHILD", "CHOSEN BY THE PEOPLE", "A COUNCIL OF THREE"),
        ("WITH BLOOD ON HIS HAND", "LIFE IN THE TEMPLE", "SCHOLASTIC ARGUMENTS"),
        ("A GIFT TO A KING", "SUMMONED TO HEAVEN", "A MODEL OF PERFECTION", "A CONFUSION OF PROMISES"),
        ("THE BIRTH OF A CHILD", "OF THE RULER OF THE WORLD", "A FALSE ACCUSATION", "A POOR SCHOLAR"),
        ("THE GUARD SLEEPS",),
        ("RETURN OF A LOVED ONE", "DEATH OF A KING", "A KING IS CROWNED"),
        ("TRIAL BEFORE THE COUNCIL",),
        ("THE SACRIFICE IS READY", "BEHOLD THE HEIR APPARENT", "CHIEF OF THE REBELS", "CONSPIRATORS DISCOVERED"),
        ("DEFEAT OF A PLOT", "AN INNOCENT TRAITOR", "TAKEN TO THE WEST", "THE PEOPLE ARE HOSTILE"),
        ("THE ACCUSER IS SILENCED", "A SON TAKES POWER", "SWORDS CROSS IN ANGER", "THE EARTH TREMBLES"),
        ("KING WITH NO CROWN", "TRIED BY PRIESTS", "CRUCIFIED IN CHAINS", "A LOYAL HEART",
         "A FRIENDS ASSISTANCE"),
        ("A TRIAL FOR TREASON", "THE VERDICT IS DEATH", "A SECRET BURIAL"),
        ("DEATH IN THE OLD RELIGION", "AMONG HIS OWN PEOPLE", "A GREAT SACRIFICE", "AN EARLY GRAVE",
         "A PEACEFUL CONCLUSION", "A FALSE ACCUSATION"),
        ["key goes here"]
    ),

    'washington': (
        ("CHOSEN BY THE PEOPLE", "A COUNCIL OF THREE"),
        ("A GENERAL IS CHOSEN", "TO THE FIRST OF THE HOUSE"),
        ("THE HONEST LUMBERJACK", "A MODEL OF PERFECTION", "A CONFUSION OF PROMISES", 'FOR A FRIENDS HAPPINESS',),
        ("ONE OF SIX", "A FALSE ACCUSATION"),
        ("TOBACCO FOR LODGING", "SOLDIER IN THE SOUTH", "REBELS IN THE SOUTH"),
        ("HE CHANGED HIS COAT", "A MARRIAGE ARRANGED", "HOW DO KING TOSH", "A KING IS CROWNED"),
        ("A WIDOW AND CHILDREN", "HE SAT FOR A PICTURE", "TRIAL BEFORE THE COUNCIL"),
        ("CHIEF OF THE REBELS", "A MAN OF LETTERS", "HE REJECTS A PROPOSAL", "THE OLD RULER IS BANISHED"),
        ("FIGHT FOR FREEDOM", "AN INNOCENT TRAITOR", "A COUNCIL OF REGENTS", "THE PEOPLE ARE HOSTILE"),
        ("AMERICA DISCOVERS ENGLAND", "A SON TAKES POWER"),
        ("AN EMPIRE DIVIDED", "KING WITH NO CROWN"),
        ("FOUNDER OF A NATION", "SOME SLAVES GO FREE", "A TRIAL FOR TREASON"),
        ("A PET TAKES FLIGHT",),
        ["key goes here"]
    ),

    'journey': (  # 0.6 seconds
        ("RETURNING HOME", "THE SHIPS ARE AT SEA"),
        ("THE PIRATES WON THE PRIZE",),
        ("SUMMONED TO HEAVEN", "HE RETURNS WITH HER FATHER", "JOURNEY BY WATER", "JOURNEY IN DISGUISE"),
        ("JOURNEY BY RIVER",),
        ("SET SAIL FOR THE SOUTH",),
        ("RETURN OF A LOVED ONE",),
        ("AN AMERICAN SAILOR",),
        ("A VOYAGE TO FRANCE",),
        ("TAKEN TO THE WEST", "A VOYAGE BY WATER", "JOURNEY IN THE DARK"),
        ("PARTING OF FRIENDS", "AMERICA DISCOVERS ENGLAND", "THE MOUNTAIN OF GROG"),
        ("THEY RETURN SEPARATELY", "TO A FOOLS PARADISE"),
        ("PARTING OF FRIENDS", "JOURNEY BY SEA", "STORMY CROSSING", "THE SHIPS ARE FOUND",
         "AN ARDUOUS JOURNEY", "IN A DISTANT LAND"),
        ("LAND OF THE CYCLOPS", "A PET TAKES FLIGHT"),
        ["key goes here"]
    ),

    'butterflies': (
        ("OF A PRINCE IN THE EAST", "IN ELIZABETHS GARDEN"),
        ("THE PIRATES WON THE PRIZE", "WITH BLOOD ON HIS HAND", "A GENERAL IS CHOSEN"),
        ("TIME OF LAMPLIGHT", "A MESSAGE FROM JUPITER", "IN A CHAMBER OF TREES", "THE SKY FOR A ROOF"),
        ("A PEANUT FOR SEMELIA", "IN THE SAVAGE FOREST", "LONDON JOINS PARIS"),
        ("PRISONER IN THE WOOD", "A COMMODORE AT TRAFALGAR", "EGGS MUST BE BROKEN", "A VELVET SUIT"),
        ("THE ADMIRALS PARTY", "APRICOTS AND NECTARINES"),
        ("A WIDOW AND CHILDREN", "AN AMERICAN SAILOR", "BEWARE OF POISON"),
        ("THE DISTANT MOUNTAINS", "A VOYAGE TO FRANCE",),
        ("EMPEROR WANG MOURNS", "BEHOLD JUPITERS CHILDREN", "A COUNCIL OF REGENTS"),
        ("THE LADIES MUST AGREE", "THE MOUNTAIN OF GROG", "A CHANGE OF CLOTHING", "AMERICA DISCOVERS ENGLAND"),
        ("KING WITH NO CROWN", "TO A FOOLS PARADISE", "HER SLAVE JEWEL BEARER"),
        ("JOURNEY BY SEA", "THE VERDICT IS DEATH", "AN ARDUOUS JOURNEY"),
        ("LAND OF THE CYCLOPS", "A PET TAKES FLIGHT", "A PEACEFUL CONCLUSION"),
        ["key goes here"]
    ),

    'all': [[] for _ in range(14)]
}

# """
keys = (
    ("EUJGZBBEIKUVQFQCGKNQ", 8),
    ("JBFCEGMQREYHBVHNLVZP", 13),
    ("DUJJTWNDXAGTBKMJVTMD", 11),
    ("VMHOKWMIZWKZTJDYFKSG", 1),
    ("EKSYCFHEQTWUBEBTELCO", 13),
    ("XBNVKXBPNGCYQSIUPJLV", 5),
    ("KJYQKGAWZYAGVEJVKGUK", 2),
    ("IVYIZJJOLFOGQOPJJEXY", 14),
    ("EGEQOIOTFADVVJNNSGDL", 5),
    ("ZGTEVNDRXKOSNHIHAEMU", 3),
    ("TFRQAMYUWOLXKTDNBHIW", 1),
    ("CPMVGKHPMEGPIDHQFJDF", 9),
    ("WYTAPRVJHYHUJLTUTMVZ", 5),
    ("JLIFDEPEKIUTCRBLWRLG", 10),
    ("BKXKWEBUZOXSZCIFLAYC", 7),
    ("PPRBIMCYJVRLKVXPUUGF", 11),
)
"""
keys = (
    ("EUJGZBBEIKUVQFQCGKNQ", 1),
    ("JBFCEGMQREYHBVHNLVZP", 1),
    ("DUJJTWNDXAGTBKMJVTMD", 1),
    ("VMHOKWMIZWKZTJDYFKSG", 1),
    ("EKSYCFHEQTWUBEBTELCO", 1),
    ("XBNVKXBPNGCYQSIUPJLV", 1),
    ("KJYQKGAWZYAGVEJVKGUK", 1),
    ("IVYIZJJOLFOGQOPJJEXY", 1),
    ("EGEQOIOTFADVVJNNSGDL", 1),
    ("ZGTEVNDRXKOSNHIHAEMU", 1),
    ("TFRQAMYUWOLXKTDNBHIW", 1),
    ("CPMVGKHPMEGPIDHQFJDF", 1),
    ("WYTAPRVJHYHUJLTUTMVZ", 1),
    ("JLIFDEPEKIUTCRBLWRLG", 1),
    ("BKXKWEBUZOXSZCIFLAYC", 1),
    ("PPRBIMCYJVRLKVXPUUGF", 1)
)
"""
# 1 1 2 3 5 5 5 7 8 9 10 11 11 13 13 14

# 1 1 2 3 5 8 13

"""
("HMTFSDTGQJCIAZLDDCWB", 1),
("APYHZHJMCWURMHPFWVIK", 1),
("JQQZOZRUZPZRQSHBUQJE", 1),
("FZYMVFQGZOKDLJMIMPGQ", 1),
("HTJXDUFPLITWUYLCLTSO", 1),
("HMTFSDTGQJCIAZLDDCWB", 5),
("APYHZHJMCWURMHPFWVIK", 5),
("JQQZOZRUZPZRQSHBUQJE", 5),
("FZYMVFQGZOKDLJMIMPGQ", 5),
("HTJXDUFPLITWUYLCLTSO", 5),
("HMTFSDTGQJCIAZLDDCWB", 13),
("APYHZHJMCWURMHPFWVIK", 13),
("JQQZOZRUZPZRQSHBUQJE", 13),
("FZYMVFQGZOKDLJMIMPGQ", 13),
("HTJXDUFPLITWUYLCLTSO", 13)
"""

# populate 'all'
for i, page in enumerate(BOOK):
    for j, line in enumerate(page):
        LINES['all'][i].append(line)

LINES['all'][-1] = ['key goes here']
