LINES = {
    'computer': (  # 0.37 seconds
        ("IN THE LAND OF THE DRAGON",),
        ("EXCHANGE OF APPLES",),
        ("A MESSAGE FROM JUPITER",),
        ("A PEANUT FOR SEMELIA",),
        ("A COMMODORE AT TRAFALGAR",),
        ("APRICOTS AND NECTARINES",),
        ("THE GENIE IN THE CHURCH",),
        ("SHARP DAGGERS CONCEALED",),
        ("EMPEROR WANG MOURNS",),
        ("HE CARRIES THE TORCH",),
        ("THE VICTOR REJOICES",),
        ("A FORTUNE IS LOST",),
        ("A PET TAKES FLIGHT",),
        ["key goes here"]
    ),

    'jesus': (  # 2m 24.8 seconds
        ("AN UNWANTED CHILD", "CHOSEN BY THE PEOPLE", "A COUNCIL OF THREE"),
        ("WITH BLOOD ON HIS HAND", "LIFE IN THE TEMPLE", "SCHOLASTIC ARGUMENTS"),
        ("A GIFT TO A KING", "SUMMONED TO HEAVEN", "A MODEL OF PERFECTION", "A CONFUSION OF PROMISES"),
        ("THE BIRTH OF A CHILD", "OF THE RULER OF THE WORLD", "A FALSE ACCUSATION", "A POOR SCHOLAR"),
        ("THE GUARD SLEEPS",),
        ("RETURN OF A LOVED ONE", "DEATH OF A KING", "A KING IS CROWNED"),
        ("TRIAL BEFORE THE COUNCIL",),
        ("THE SACRIFICE IS READY", "BEHOLD THE HEIR APPARENT", "CHIEF OF THE REBELS", "CONSPIRATORS DISCOVERED"),
        ("DEFEAT OF A PLOT", "AN INNOCENT TRAITOR", "TAKEN TO THE WEST", "THE PEOPLE ARE HOSTILE"),
        ("THE ACCUSER IS SILENCED", "A SON TAKES POWER", "SWORDS CROSS IN ANGER", "THE EARTH TREMBLES"),
        ("KING WITH NO CROWN", "TRIED BY PRIESTS", "CRUCIFIED IN CHAINS", "A LOYAL HEART",
         "A FRIENDS ASSISTANCE"),
        ("A TRIAL FOR TREASON", "THE VERDICT IS DEATH", "A SECRET BURIAL"),
        ("DEATH IN THE OLD RELIGION", "AMONG HIS OWN PEOPLE", "A GREAT SACRIFICE", "AN EARLY GRAVE",
         "A PEACEFUL CONCLUSION", "A FALSE ACCUSATION"),
        ["key goes here"]
    ),

    'washington': (
        ("CHOSEN BY THE PEOPLE", "A COUNCIL OF THREE"),
        ("A GENERAL IS CHOSEN", "TO THE FIRST OF THE HOUSE", "CREATED TEN OF TEN"),
        ("THE HONEST LUMBERJACK", "A MODEL OF PERFECTION", "A CONFUSION OF PROMISES", 'FOR A FRIENDS HAPPINESS',),
        ("ONE OF SIX", "A FALSE ACCUSATION"),
        ("TOBACCO FOR LODGING", "SOLDIER IN THE SOUTH", "REBELS IN THE SOUTH"),
        ("HE CHANGED HIS COAT", "A MARRIAGE ARRANGED", "HOW DO KING TOSH", "A KING IS CROWNED"),
        ("A WIDOW AND CHILDREN", "HE SAT FOR A PICTURE", "HE WEARS A DIFFERENT CROWN",
         "TRIAL BEFORE THE COUNCIL", "HE DOUBTS HIS SON", "THE NONCONFORMIST"),
        ("CHIEF OF THE REBELS", "A MAN OF LETTERS", "HE REJECTS A PROPOSAL", "THE OLD RULER IS BANISHED"),
        ("FIGHT FOR FREEDOM", "AN INNOCENT TRAITOR", "A COUNCIL OF REGENTS", "THE PEOPLE ARE HOSTILE"),
        ("AMERICA DISCOVERS ENGLAND", "A SON TAKES POWER"),
        ("AN EMPIRE DIVIDED", "KING WITH NO CROWN"),
        ("FOUNDER OF A NATION", "SOME SLAVES GO FREE", "A TRIAL FOR TREASON"),
        ("A PET TAKES FLIGHT",),
        ["key goes here"]
    ),

    'journey': (  # 0.6 seconds
        ("RETURNING HOME", "THE SHIPS ARE AT SEA"),
        ("THE PIRATES WON THE PRIZE",),
        ("SUMMONED TO HEAVEN", "HE RETURNS WITH HER FATHER", "JOURNEY BY WATER", "JOURNEY IN DISGUISE"),
        ("JOURNEY BY RIVER",),
        ("SET SAIL FOR THE SOUTH",),
        ("RETURN OF A LOVED ONE",),
        ("AN AMERICAN SAILOR",),
        ("A VOYAGE TO FRANCE",),
        ("TAKEN TO THE WEST", "A VOYAGE BY WATER", "JOURNEY IN THE DARK"),
        ("PARTING OF FRIENDS", "AMERICA DISCOVERS ENGLAND", "THE CAPTIVES ESCAPE", "THEY RETURN TO THE JEWEL",
         "THE MOUNTAIN OF GROG"),
        ("THEY RETURN SEPARATELY", "TO A FOOLS PARADISE"),
        ("PARTING OF FRIENDS", "JOURNEY BY SEA", "STORMY CROSSING", "THE SHIPS ARE FOUND",
         "AN ARDUOUS JOURNEY", "IN A DISTANT LAND"),
        ("LAND OF THE CYCLOPS", "A PET TAKES FLIGHT"),
        ["key goes here"]
    )
}

keys = (
    ("EUJGZBBEIKUVQFQCGKNQ", 8),
    ("JBFCEGMQREYHBVHNLVZP", 13),
    ("DUJJTWNDXAGTBKMJVTMD", 11),
    ("VMHOKWMIZWKZTJDYFKSG", 1),
    ("EKSYCFHEQTWUBEBTELCO", 13),
    ("XBNVKXBPNGCYQSIUPJLV", 5),
    ("KJYQKGAWZYAGVEJVKGUK", 2),
    ("IVYIZJJOLFOGQOPJJEXY", 14),
    ("EGEQOIOTFADVVJNNSGDL", 5),
    ("ZGTEVNDRXKOSNHIHAEMU", 3),
    ("TFRQAMYUWOLXKTDNBHIW", 1),
    ("CPMVGKHPMEGPIDHQFJDF", 9),
    ("WYTAPRVJHYHUJLTUTMVZ", 5),
    ("JLIFDEPEKIUTCRBLWRLG", 10),
    ("BKXKWEBUZOXSZCIFLAYC", 7),
    ("PPRBIMCYJVRLKVXPUUGF", 11)
)

"""
("HMTFSDTGQJCIAZLDDCWB", 1),
("APYHZHJMCWURMHPFWVIK", 1),
("JQQZOZRUZPZRQSHBUQJE", 1),
("FZYMVFQGZOKDLJMIMPGQ", 1),
("HTJXDUFPLITWUYLCLTSO", 1),
("HMTFSDTGQJCIAZLDDCWB", 5),
("APYHZHJMCWURMHPFWVIK", 5),
("JQQZOZRUZPZRQSHBUQJE", 5),
("FZYMVFQGZOKDLJMIMPGQ", 5),
("HTJXDUFPLITWUYLCLTSO", 5),
("HMTFSDTGQJCIAZLDDCWB", 13),
("APYHZHJMCWURMHPFWVIK", 13),
("JQQZOZRUZPZRQSHBUQJE", 13),
("FZYMVFQGZOKDLJMIMPGQ", 13),
("HTJXDUFPLITWUYLCLTSO", 13)
"""
