from book import BOOK

LINES = {
    'computer': [  # 0.37 seconds
        ["IN THE LAND OF THE DRAGON",],
        ["EXCHANGE OF APPLES",],
        ["A MESSAGE FROM JUPITER",],
        ["A PEANUT FOR SEMELIA",],
        ["A COMMODORE AT TRAFALGAR",],
        ["APRICOTS AND NECTARINES",],
        ["THE GENIE IN THE CHURCH",],
        ["SHARP DAGGERS CONCEALED",],
        ["EMPEROR WANG MOURNS",],
        ["HE CARRIES THE TORCH",],
        ["THE VICTOR REJOICES",],
        ["A FORTUNE IS LOST",],
        ["A PET TAKES FLIGHT",],
        ["key goes here"]
    ],

    'jesus': [  # 2m 24.8 seconds
        ["AN UNWANTED CHILD", "A COUNCIL OF THREE", "RETURNING HOME", "OF LOVE BETWEEN ENEMIES"],
        ["WITH BLOOD ON HIS HAND", "LIFE IN THE TEMPLE", "SCHOLASTIC ARGUMENTS", "THEY MUST DANCE", "TO THE FIRST OF THE HOSUE"],
        ["A GIFT TO A KING", "SUMMONED TO HEAVEN", "A MODEL OF PERFECTION"],
        ["THE BIRTH OF A CHILD", "OF THE RULER OF THE WORLD", "A FALSE ACCUSATION", "A PLEA FOR MERCY"],
        ["THE GUARD SLEEPS", "A CITY IS LIBERATED", "SOLDIER IN THE SOUTH"],
        ["RETURN OF A LOVED ONE", "DEATH OF A KING", "A KING IS CROWNED"],
        ["TRIAL BEFORE THE COUNCIL","ENTER THE HERO", "AN AGENT OF PROTEST", "A PRISONER IS TAKEN", "HE WEATS A DIFFERENT CROWN", "LOYALTIES ARE DIVIDED", "WOUNDED BY THE TRUTH"],
        ["THE SACRIFICE IS READY", "BEHOLD THE HEIR APPARENT", "CHIEF OF THE REBELS", "CONSPIRATORS DISCOVERED", "SHE BEARS HIM A CHILD"],
        ["DEFEAT OF A PLOT", "AN INNOCENT TRAITOR", "THE PEOPLE ARE HOSTILE", "FIGHT FOR FREEDOM"],
        ["THE ACCUSER IS SILENCED", "A SON TAKES POWER", "THE EARTH TREMBLES"],
        ["KING WITH NO CROWN", "TRIED BY PRIESTS", "CRUCIFIED IN CHAINS", "A LOYAL HEART"],
        ["A FRIENDS ASSISTANCE", "AN EMPIRE DIVIDED"],
        ["A TRIAL FOR TREASON", "THE VERDICT IS DEATH", "CAST INTO PRISON", "A SECRET BURIAL"],
        ["DEATH IN THE OLD RELIGION", "AMONG HIS OWN PEOPLE", "A GREAT SACRIFICE", "AN EARLY GRAVE",
         "A FALSE ACCUSATION", "BURIED ALIVE", "A PAINFUL END"],
        ["key goes here"]
    ],

    'washington': [
        ["CHOSEN BY THE PEOPLE", "A COUNCIL OF THREE"],
        ["A GENERAL IS CHOSEN", "TO THE FIRST OF THE HOUSE", "AMETHYSTS CHILD"],
        ["THE HONEST LUMBERJACK", "A MODEL OF PERFECTION", "A CONFUSION OF PROMISES", 'FOR A FRIENDS HAPPINESS',],
        ["ONE OF SIX", "A FALSE ACCUSATION"],
        ["A VELVET SUIT", "TOBACCO FOR LODGING", "SOLDIER IN THE SOUTH", "REBELS IN THE SOUTH", "SHELTERED BY BANKS", "JOURNEY BY RIVER", "OF THE RULER OF THE WORLD"],
        ["HE CHANGED HIS COAT", "A MARRIAGE ARRANGED", "HOW DO KING TOSH", "A KING IS CROWNED"],
        ["AN AMERICAN SAILOR", "A WIDOW AND CHILDREN", "HE SAT FOR A PICTURE", "TRIAL BEFORE THE COUNCIL"],
        ["CHIEF OF THE REBELS", "A MAN OF LETTERS", "HE REJECTS A PROPOSAL", "THE OLD RULER IS BANISHED", "A SOCIAL LION"],
        ["FIGHT FOR FREEDOM", "AN INNOCENT TRAITOR", "A COUNCIL OF REGENTS", "THE PEOPLE ARE HOSTILE", "A DUAL IN COURT"],
        ["AMERICA DISCOVERS ENGLAND", "A SON TAKES POWER", "A CHANGE OF CLOTHING", "THE RETURN OF A GIFT"],
        ["AN EMPIRE DIVIDED", "KING WITH NO CROWN", "A GERMAN CUTS HIM DOWN"],
        ["FOUNDER OF A NATION", "SOME SLAVES GO FREE", "A TRIAL FOR TREASON", "THE LIGHT OF VICTORY", "STORMY CROSSING"],
        ["A PET TAKES FLIGHT", "A PEACEFUL CONCLUSION", "A PAINFUL END", "A GREAT SACRIFICE"],
        ["key goes here"]
    ],

    'journey': [  # 0.6 seconds
        ["RETURNING HOME", "THE SHIPS ARE AT SEA"],
        ["THE PIRATES WON THE PRIZE",],
        ["SUMMONED TO HEAVEN", "HE RETURNS WITH HER FATHER", "JOURNEY BY WATER", "JOURNEY IN DISGUISE"],
        ["JOURNEY BY RIVER",],
        ["SET SAIL FOR THE SOUTH",],
        ["RETURN OF A LOVED ONE",],
        ["AN AMERICAN SAILOR",],
        ["A VOYAGE TO FRANCE",],
        ["TAKEN TO THE WEST", "A VOYAGE BY WATER", "JOURNEY IN THE DARK"],
        ["PARTING OF FRIENDS", "AMERICA DISCOVERS ENGLAND", "THE MOUNTAIN OF GROG"],
        ["THEY RETURN SEPARATELY", "TO A FOOLS PARADISE"],
        ["PARTING OF FRIENDS", "JOURNEY BY SEA", "STORMY CROSSING", "THE SHIPS ARE FOUND"],
        ["AN ARDUOUS JOURNEY", "IN A DISTANT LAND"],
        ["LAND OF THE CYCLOPS", "A PET TAKES FLIGHT"],
        ["key goes here"]
    ],

    'butterflies': [
        ["OF A PRINCE IN THE EAST", "IN ELIZABETHS GARDEN"],
        ["THE PIRATES WON THE PRIZE", "WITH BLOOD ON HIS HAND", "A GENERAL IS CHOSEN"],
        ["TIME OF LAMPLIGHT", "A MESSAGE FROM JUPITER", "IN A CHAMBER OF TREES", "THE SKY FOR A ROOF", "A GIFT TO A KING"],
        ["A PEANUT FOR SEMELIA", "IN THE SAVAGE FOREST", "LONDON JOINS PARIS", "THE GRAND VIZIER"],
        ["PRISONER IN THE WOOD", "A COMMODORE AT TRAFALGAR", "EGGS MUST BE BROKEN", "A VELVET SUIT"],
        ["THE ADMIRALS PARTY", "APRICOTS AND NECTARINES", "A BANQUET OF KINGS", "DEATH OF A KING", "A KING IS CROWNED", "HOW DO KING TOSH"],
        ["A WIDOW AND CHILDREN", "ENTER THE HERO"],
        ["THE DISTANT MOUNTAINS", "BEHOLD THE HEIR APPARENT"],
        ["EMPEROR WANG MOURNS", "BEHOLD JUPITERS CHILDREN", "A COUNCIL OF REGENTS"],
        ["THE LADIES MUST AGREE", "THE MOUNTAIN OF GROG", "A CHANGE OF CLOTHING", "AMERICA DISCOVERS ENGLAND", "A SON TAKES POWER"],
        ["KING WITH NO CROWN", "TO A FOOLS PARADISE", "HER SLAVE JEWEL BEARER", "AN EMPIRE DIVIDED"],
        ["JOURNEY BY SEA", "THE VERDICT IS DEATH"],
        ["LAND OF THE CYCLOPS", "A PET TAKES FLIGHT" ],
        ["key goes here"]
    ],

    'fruit': [
        ["IN THE LAND OF THE DRAGON"],
        ["EXCHANGE OF APPLES", "THE DRAGON SLAYER"],
        ["THE SMELL OF LEATHER", "IN A CHAMBER OF TREES"],
        ["A PEANUT FOR SEMELIA", "JOURNEY BY RIVER"],
        ["PRISONER IN THE WOOD", "A VELVET SUIT"],
        ["APRICOTS AND NECTARINES"],
        ["HE WEARS A DIFFERENT CROWN"],
        ["SHARP DAGGERS CONCEALED"],
        ["BEHOLD JUPITERS CHILDREN", "THE DRAGON IS WOUNDED", "A SHIELD OF FIRE", "HE CARRIES THE TORCH", "RETURN TO THE JEWEL", "A COUNCIL OF REGENTS"],
        ["HE CARRIES THE TORCH", "SWORDS CROSS IN ANGER", "THE EARTH TREMBLES", "THEY RETURN TO THE JEWEL"],
        ["HER SLAVE JEWEL BEARER", "A KING WITH NO CROWN", "A LOYAL HEART", "TO A FOOLS PARADISE"],
        ["JOURNEY BY SEA"],
        ["LAND OF THE CYCLOPS"],
        ["key goes here"]
    ],

    'misspellings': [
        ["ONE FORGED BY WEYLAND"],
        [""],
        [""],
        [""],
        [""],
        ["ACROBATS AND CROWNS"],
        ["A WIDOW AND CHILDREN"],
        [""],
        ["A DUAL IN COURT"],
        [""],
        [""],
        [""],
        [""],
        ["key goes here"]
    ],

    'omai': [
        ["OF A PRINCE IN THE EAST", "A MAN OF NATURE", "OF LOVE BETWEEN ENEMIES", "RETURNING HOME", "THE TRAVELLERS GUARD", "SHIELD OF FLOWERS", "THE SHIPS ARE AT SEA"],
        ["DISTURBED BY DISCOVERY"],
        ["THE SKY FOR A ROOF", "A GIFT TO A KING", "JOURNEY BY WATER", "A CONFUSION OF PROMISES"],
        ["SHELTERED BY BANKS"],
        ["A VELVET SUIT"],
        ["HOW DO KING TOSH"],
        ["HE SAT FOR A PICTURE", "ENTER THE HERO", "A GENIE IN THE CHURCH", "THE NONCONFORMIST", "AN AMERICAN SAILOR", "HE WEARS A DIFFERENT CROWN", "LOYALTIES ARE DIVIDED", "HE DOUBTS HIS SON", "A LOVERS TRYST"],
        ["A SOCIAL LION"],
        ["TAKEN TO THE WEST", "A VOYAGE BY WATER"],
        ["A CHANGE OF CLOTHING", "SWORDS CROSS IN ANGER", "THE EARTH TREMBLES"],
        ["KING WITH NO CROWN", "AN EMPIRE DIVIDED", "A LOYAL HEART"],
        ["JOURNEY BY SEA", "THE LIGHT OF VICTORY", "STORMY CROSSING", "THE SHIPS ARE FOUND", "AN ARDUOUS JOURNEY", "IN A DISTANT LAND"],
        ["HE BOWS TO THE SWORD"],
        ["key goes here"]
    ],

    'rulers': [
        ["OF A PRINCE IN THE EAST"],
        ["A GENERAL IS CHOSEN"],
        ["A GIFT TO A KING"],
        ["THE GRAND VIZIER"],
        ["A TYRANT IS BORN", "A COMMODORE AT TRAFALGAR"],
        ["A BANQUET OF KINGS", "THE ADMIRALS PARTY", "DEATH OF A KING", "A KING IS CROWNED", "HOW DO KING TOSH"],
        ["ENTER THE HERO", "THE GENIE IN THE CHURCH", "TRIAL BEFORE THE COUNCIL"],
        ["BEHOLD THE HEIR APPARENT", "CHIEF OF THE REBELS", "THE OLD RULER IS BANISHED"],
        ["EMPEROR WANG MOURNS", "A COUNCIL OF REGENTS"],
        ["A SON TAKES POWER"],
        ["KING WITH NO CROWN", "AN EMPIRE DIVIDED"],
        ["FOUNDER OF A NATION"],
        ["SHE WIELDS POWER", "LAND OF THE CYCLOPS", "AMONG HIS OWN PEOPLE"],
        ["key goes here"]
    ],

    'all': [[] for _ in range(14)]
}

# """
keys = [
    ["EUJGZBBEIKUVQFQCGKNQ", 8],
    ["JBFCEGMQREYHBVHNLVZP", 13],
    ["DUJJTWNDXAGTBKMJVTMD", 11],
    ["VMHOKWMIZWKZTJDYFKSG", 1],
    ["EKSYCFHEQTWUBEBTELCO", 13],
    ["XBNVKXBPNGCYQSIUPJLV", 5],
    ["KJYQKGAWZYAGVEJVKGUK", 2],
    ["IVYIZJJOLFOGQOPJJEXY", 14],
    ["EGEQOIOTFADVVJNNSGDL", 5],
    ["ZGTEVNDRXKOSNHIHAEMU", 3],
    ["TFRQAMYUWOLXKTDNBHIW", 1],
    ["CPMVGKHPMEGPIDHQFJDF", 9],
    ["WYTAPRVJHYHUJLTUTMVZ", 5],
    ["JLIFDEPEKIUTCRBLWRLG", 10],
    ["BKXKWEBUZOXSZCIFLAYC", 7],
    ["PPRBIMCYJVRLKVXPUUGF", 11],
]
"""
keys = [
    ["EUJGZBBEIKUVQFQCGKNQ", 1],
    ["JBFCEGMQREYHBVHNLVZP", 1],
    ["DUJJTWNDXAGTBKMJVTMD", 1],
    ["VMHOKWMIZWKZTJDYFKSG", 1],
    ["EKSYCFHEQTWUBEBTELCO", 1],
    ["XBNVKXBPNGCYQSIUPJLV", 1],
    ["KJYQKGAWZYAGVEJVKGUK", 1],
    ["IVYIZJJOLFOGQOPJJEXY", 1],
    ["EGEQOIOTFADVVJNNSGDL", 1],
    ["ZGTEVNDRXKOSNHIHAEMU", 1],
    ["TFRQAMYUWOLXKTDNBHIW", 1],
    ["CPMVGKHPMEGPIDHQFJDF", 1],
    ["WYTAPRVJHYHUJLTUTMVZ", 1],
    ["JLIFDEPEKIUTCRBLWRLG", 1],
    ["BKXKWEBUZOXSZCIFLAYC", 1],
    ["PPRBIMCYJVRLKVXPUUGF", 1)
]
"""
# 1 1 2 3 5 5 5 7 8 9 10 11 11 13 13 14

# 1 1 2 3 5 8 13

"""
["HMTFSDTGQJCIAZLDDCWB", 1],
["APYHZHJMCWURMHPFWVIK", 1],
["JQQZOZRUZPZRQSHBUQJE", 1],
["FZYMVFQGZOKDLJMIMPGQ", 1],
["HTJXDUFPLITWUYLCLTSO", 1],
["HMTFSDTGQJCIAZLDDCWB", 5],
["APYHZHJMCWURMHPFWVIK", 5],
["JQQZOZRUZPZRQSHBUQJE", 5],
["FZYMVFQGZOKDLJMIMPGQ", 5],
["HTJXDUFPLITWUYLCLTSO", 5],
["HMTFSDTGQJCIAZLDDCWB", 13],
["APYHZHJMCWURMHPFWVIK", 13],
["JQQZOZRUZPZRQSHBUQJE", 13],
["FZYMVFQGZOKDLJMIMPGQ", 13],
["HTJXDUFPLITWUYLCLTSO", 13]
"""

# populate 'all'
for i, page in enumerate(BOOK):
    for j, line in enumerate(page):
        LINES['all'][i].append(line)

LINES['all'][-1] = ['key goes here']
